/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as BusinessMemoryRouteImport } from './routes/business-memory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AddRecordRouteImport } from './routes/add-record'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsNewRouteImport } from './routes/conversations.new'
import { Route as ConversationsIdRouteImport } from './routes/conversations.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMemoryRoute = BusinessMemoryRouteImport.update({
  id: '/business-memory',
  path: '/business-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRecordRoute = AddRecordRouteImport.update({
  id: '/add-record',
  path: '/add-record',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsNewRoute = ConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/conversations/$id'
    | '/conversations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/conversations/$id'
    | '/conversations/new'
  id:
    | '__root__'
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/conversations/$id'
    | '/conversations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRecordRoute: typeof AddRecordRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AuthRoute: typeof AuthRoute
  BusinessMemoryRoute: typeof BusinessMemoryRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsNewRoute: typeof ConversationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-memory': {
      id: '/business-memory'
      path: '/business-memory'
      fullPath: '/business-memory'
      preLoaderRoute: typeof BusinessMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-record': {
      id: '/add-record'
      path: '/add-record'
      fullPath: '/add-record'
      preLoaderRoute: typeof AddRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/new': {
      id: '/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof ConversationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRecordRoute: AddRecordRoute,
  AiAssistantRoute: AiAssistantRoute,
  AuthRoute: AuthRoute,
  BusinessMemoryRoute: BusinessMemoryRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsNewRoute: ConversationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
