/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BusinessSetupRouteImport } from './routes/business-setup'
import { Route as BusinessMemoryRouteImport } from './routes/business-memory'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AddRecordRouteImport } from './routes/add-record'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsBusinessRouteImport } from './routes/settings.business'
import { Route as ScannerNewRouteImport } from './routes/scanner.new'
import { Route as ScannerHistoryRouteImport } from './routes/scanner.history'
import { Route as ScannerScanIdRouteImport } from './routes/scanner.$scanId'
import { Route as RecordsManualRouteImport } from './routes/records.manual'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersMergeHistoryRouteImport } from './routes/customers.merge-history'
import { Route as CustomersDuplicatesRouteImport } from './routes/customers.duplicates'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ConversationsNewRouteImport } from './routes/conversations.new'
import { Route as ConversationsIdRouteImport } from './routes/conversations.$id'
import { Route as AdminYarngptRouteImport } from './routes/admin.yarngpt'
import { Route as ScannerScanIdConvertRouteImport } from './routes/scanner.$scanId.convert'
import { Route as OrdersIdPaymentRouteImport } from './routes/orders.$id.payment'
import { Route as CustomersDuplicatesGroupIdRouteImport } from './routes/customers.duplicates.$groupId'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSetupRoute = BusinessSetupRouteImport.update({
  id: '/business-setup',
  path: '/business-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMemoryRoute = BusinessMemoryRouteImport.update({
  id: '/business-memory',
  path: '/business-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRecordRoute = AddRecordRouteImport.update({
  id: '/add-record',
  path: '/add-record',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBusinessRoute = SettingsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => SettingsRoute,
} as any)
const ScannerNewRoute = ScannerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScannerRoute,
} as any)
const ScannerHistoryRoute = ScannerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ScannerRoute,
} as any)
const ScannerScanIdRoute = ScannerScanIdRouteImport.update({
  id: '/$scanId',
  path: '/$scanId',
  getParentRoute: () => ScannerRoute,
} as any)
const RecordsManualRoute = RecordsManualRouteImport.update({
  id: '/records/manual',
  path: '/records/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersMergeHistoryRoute = CustomersMergeHistoryRouteImport.update({
  id: '/merge-history',
  path: '/merge-history',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersDuplicatesRoute = CustomersDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const ConversationsNewRoute = ConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYarngptRoute = AdminYarngptRouteImport.update({
  id: '/admin/yarngpt',
  path: '/admin/yarngpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerScanIdConvertRoute = ScannerScanIdConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => ScannerScanIdRoute,
} as any)
const OrdersIdPaymentRoute = OrdersIdPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => OrdersIdRoute,
} as any)
const CustomersDuplicatesGroupIdRoute =
  CustomersDuplicatesGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => CustomersDuplicatesRoute,
  } as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/yarngpt': typeof AdminYarngptRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/duplicates': typeof CustomersDuplicatesRouteWithChildren
  '/customers/merge-history': typeof CustomersMergeHistoryRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/records/manual': typeof RecordsManualRoute
  '/scanner/$scanId': typeof ScannerScanIdRouteWithChildren
  '/scanner/history': typeof ScannerHistoryRoute
  '/scanner/new': typeof ScannerNewRoute
  '/settings/business': typeof SettingsBusinessRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/duplicates/$groupId': typeof CustomersDuplicatesGroupIdRoute
  '/orders/$id/payment': typeof OrdersIdPaymentRoute
  '/scanner/$scanId/convert': typeof ScannerScanIdConvertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/yarngpt': typeof AdminYarngptRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/duplicates': typeof CustomersDuplicatesRouteWithChildren
  '/customers/merge-history': typeof CustomersMergeHistoryRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/records/manual': typeof RecordsManualRoute
  '/scanner/$scanId': typeof ScannerScanIdRouteWithChildren
  '/scanner/history': typeof ScannerHistoryRoute
  '/scanner/new': typeof ScannerNewRoute
  '/settings/business': typeof SettingsBusinessRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/duplicates/$groupId': typeof CustomersDuplicatesGroupIdRoute
  '/orders/$id/payment': typeof OrdersIdPaymentRoute
  '/scanner/$scanId/convert': typeof ScannerScanIdConvertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-record': typeof AddRecordRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/auth': typeof AuthRoute
  '/business-memory': typeof BusinessMemoryRoute
  '/business-setup': typeof BusinessSetupRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/scanner': typeof ScannerRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/admin/yarngpt': typeof AdminYarngptRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/duplicates': typeof CustomersDuplicatesRouteWithChildren
  '/customers/merge-history': typeof CustomersMergeHistoryRoute
  '/customers/new': typeof CustomersNewRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/records/manual': typeof RecordsManualRoute
  '/scanner/$scanId': typeof ScannerScanIdRouteWithChildren
  '/scanner/history': typeof ScannerHistoryRoute
  '/scanner/new': typeof ScannerNewRoute
  '/settings/business': typeof SettingsBusinessRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/duplicates/$groupId': typeof CustomersDuplicatesGroupIdRoute
  '/orders/$id/payment': typeof OrdersIdPaymentRoute
  '/scanner/$scanId/convert': typeof ScannerScanIdConvertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/yarngpt'
    | '/conversations/$id'
    | '/conversations/new'
    | '/customers/$id'
    | '/customers/duplicates'
    | '/customers/merge-history'
    | '/customers/new'
    | '/orders/$id'
    | '/records/manual'
    | '/scanner/$scanId'
    | '/scanner/history'
    | '/scanner/new'
    | '/settings/business'
    | '/customers/$id/edit'
    | '/customers/duplicates/$groupId'
    | '/orders/$id/payment'
    | '/scanner/$scanId/convert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/yarngpt'
    | '/conversations/$id'
    | '/conversations/new'
    | '/customers/$id'
    | '/customers/duplicates'
    | '/customers/merge-history'
    | '/customers/new'
    | '/orders/$id'
    | '/records/manual'
    | '/scanner/$scanId'
    | '/scanner/history'
    | '/scanner/new'
    | '/settings/business'
    | '/customers/$id/edit'
    | '/customers/duplicates/$groupId'
    | '/orders/$id/payment'
    | '/scanner/$scanId/convert'
  id:
    | '__root__'
    | '/'
    | '/add-record'
    | '/ai-assistant'
    | '/auth'
    | '/business-memory'
    | '/business-setup'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reports'
    | '/scanner'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/admin/yarngpt'
    | '/conversations/$id'
    | '/conversations/new'
    | '/customers/$id'
    | '/customers/duplicates'
    | '/customers/merge-history'
    | '/customers/new'
    | '/orders/$id'
    | '/records/manual'
    | '/scanner/$scanId'
    | '/scanner/history'
    | '/scanner/new'
    | '/settings/business'
    | '/customers/$id/edit'
    | '/customers/duplicates/$groupId'
    | '/orders/$id/payment'
    | '/scanner/$scanId/convert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRecordRoute: typeof AddRecordRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AuthRoute: typeof AuthRoute
  BusinessMemoryRoute: typeof BusinessMemoryRoute
  BusinessSetupRoute: typeof BusinessSetupRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ScannerRoute: typeof ScannerRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AdminYarngptRoute: typeof AdminYarngptRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsNewRoute: typeof ConversationsNewRoute
  RecordsManualRoute: typeof RecordsManualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-setup': {
      id: '/business-setup'
      path: '/business-setup'
      fullPath: '/business-setup'
      preLoaderRoute: typeof BusinessSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-memory': {
      id: '/business-memory'
      path: '/business-memory'
      fullPath: '/business-memory'
      preLoaderRoute: typeof BusinessMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-record': {
      id: '/add-record'
      path: '/add-record'
      fullPath: '/add-record'
      preLoaderRoute: typeof AddRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/business': {
      id: '/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof SettingsBusinessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/scanner/new': {
      id: '/scanner/new'
      path: '/new'
      fullPath: '/scanner/new'
      preLoaderRoute: typeof ScannerNewRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/scanner/history': {
      id: '/scanner/history'
      path: '/history'
      fullPath: '/scanner/history'
      preLoaderRoute: typeof ScannerHistoryRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/scanner/$scanId': {
      id: '/scanner/$scanId'
      path: '/$scanId'
      fullPath: '/scanner/$scanId'
      preLoaderRoute: typeof ScannerScanIdRouteImport
      parentRoute: typeof ScannerRoute
    }
    '/records/manual': {
      id: '/records/manual'
      path: '/records/manual'
      fullPath: '/records/manual'
      preLoaderRoute: typeof RecordsManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/merge-history': {
      id: '/customers/merge-history'
      path: '/merge-history'
      fullPath: '/customers/merge-history'
      preLoaderRoute: typeof CustomersMergeHistoryRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/duplicates': {
      id: '/customers/duplicates'
      path: '/duplicates'
      fullPath: '/customers/duplicates'
      preLoaderRoute: typeof CustomersDuplicatesRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/conversations/new': {
      id: '/conversations/new'
      path: '/conversations/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof ConversationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/yarngpt': {
      id: '/admin/yarngpt'
      path: '/admin/yarngpt'
      fullPath: '/admin/yarngpt'
      preLoaderRoute: typeof AdminYarngptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/$scanId/convert': {
      id: '/scanner/$scanId/convert'
      path: '/convert'
      fullPath: '/scanner/$scanId/convert'
      preLoaderRoute: typeof ScannerScanIdConvertRouteImport
      parentRoute: typeof ScannerScanIdRoute
    }
    '/orders/$id/payment': {
      id: '/orders/$id/payment'
      path: '/payment'
      fullPath: '/orders/$id/payment'
      preLoaderRoute: typeof OrdersIdPaymentRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/customers/duplicates/$groupId': {
      id: '/customers/duplicates/$groupId'
      path: '/$groupId'
      fullPath: '/customers/duplicates/$groupId'
      preLoaderRoute: typeof CustomersDuplicatesGroupIdRouteImport
      parentRoute: typeof CustomersDuplicatesRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CustomersDuplicatesRouteChildren {
  CustomersDuplicatesGroupIdRoute: typeof CustomersDuplicatesGroupIdRoute
}

const CustomersDuplicatesRouteChildren: CustomersDuplicatesRouteChildren = {
  CustomersDuplicatesGroupIdRoute: CustomersDuplicatesGroupIdRoute,
}

const CustomersDuplicatesRouteWithChildren =
  CustomersDuplicatesRoute._addFileChildren(CustomersDuplicatesRouteChildren)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersDuplicatesRoute: typeof CustomersDuplicatesRouteWithChildren
  CustomersMergeHistoryRoute: typeof CustomersMergeHistoryRoute
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersDuplicatesRoute: CustomersDuplicatesRouteWithChildren,
  CustomersMergeHistoryRoute: CustomersMergeHistoryRoute,
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface OrdersIdRouteChildren {
  OrdersIdPaymentRoute: typeof OrdersIdPaymentRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdPaymentRoute: OrdersIdPaymentRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRouteWithChildren,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ScannerScanIdRouteChildren {
  ScannerScanIdConvertRoute: typeof ScannerScanIdConvertRoute
}

const ScannerScanIdRouteChildren: ScannerScanIdRouteChildren = {
  ScannerScanIdConvertRoute: ScannerScanIdConvertRoute,
}

const ScannerScanIdRouteWithChildren = ScannerScanIdRoute._addFileChildren(
  ScannerScanIdRouteChildren,
)

interface ScannerRouteChildren {
  ScannerScanIdRoute: typeof ScannerScanIdRouteWithChildren
  ScannerHistoryRoute: typeof ScannerHistoryRoute
  ScannerNewRoute: typeof ScannerNewRoute
}

const ScannerRouteChildren: ScannerRouteChildren = {
  ScannerScanIdRoute: ScannerScanIdRouteWithChildren,
  ScannerHistoryRoute: ScannerHistoryRoute,
  ScannerNewRoute: ScannerNewRoute,
}

const ScannerRouteWithChildren =
  ScannerRoute._addFileChildren(ScannerRouteChildren)

interface SettingsRouteChildren {
  SettingsBusinessRoute: typeof SettingsBusinessRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBusinessRoute: SettingsBusinessRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRecordRoute: AddRecordRoute,
  AiAssistantRoute: AiAssistantRoute,
  AuthRoute: AuthRoute,
  BusinessMemoryRoute: BusinessMemoryRoute,
  BusinessSetupRoute: BusinessSetupRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ScannerRoute: ScannerRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AdminYarngptRoute: AdminYarngptRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsNewRoute: ConversationsNewRoute,
  RecordsManualRoute: RecordsManualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
